WebBanHang/Controllers/ADQuanLySPController.cs
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class ADQuanLySPController : Controller
    {
        BanHangDataContext db = new BanHangDataContext();
        // GET: ADQuanLySP
        public ActionResult QuanLySP()
        {
            return View(db.SanPhams.Where(n => n.DaXoa == false));
        }
        [HttpGet]
        public ActionResult TaoMoi()
        {
            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(SanPham sp, HttpPostedFileBase HinhAnh)
        {

            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            //Ktra Hinh anh
            if (HinhAnh.ContentLength > 0)
            {
                var filename = Path.GetFileName(HinhAnh.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/HinhSP/"), filename);
                if (System.IO.File.Exists(path))
                {
                    ViewBag.upload = "Hình ảnh đã tồn tại";
                    return View();
                }
                else
                {
                    HinhAnh.SaveAs(path);
                    sp.HinhAnh = filename;


                }


            }
            db.SanPhams.InsertOnSubmit(sp);
            db.SubmitChanges();
            return RedirectToAction("QuanLySP");

        }
        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
            return View(sp);
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(SanPham model)
        {
           

            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", model.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", model.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", model.MaNSX);
            SanPham sp = db.SanPhams.Single(n => n.MaSP == model.MaSP);
            sp.TenSP = model.TenSP;
            sp.SoLuongTon = model.SoLuongTon;
            sp.NgayCapNhat = model.NgayCapNhat;
            sp.Moi = model.Moi;
            sp.MoTa = model.MoTa;
            sp.CauHinh = model.CauHinh;
            sp.DonGia = model.DonGia;
            
            db.SubmitChanges();
            return RedirectToAction("QuanLySP");
            
        }
        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
                if (sp == null)
                {
                    return HttpNotFound();
                }
                ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
                ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
                ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
                return View(sp);
            }
        }
        [HttpPost]
        public ActionResult Xoa(int? id,FormCollection f)
        {
            {
                if (id == null)
                {

                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
                if (sp == null)
                {
                    return HttpNotFound();
                }
                db.SanPhams.DeleteOnSubmit(sp);
                db.SubmitChanges(); ;
                return RedirectToAction("QuanLySP");

            }
        }
    }
}

WebBanHang/Controllers/ChinhQuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
namespace WebBanHang.Controllers
{
    [Authorize(Roles = "DangKy")]
    public class ChinhQuyenController : Controller
    {
        BanHangDataContext db = new BanHangDataContext();
        // GET: ChinhQuyen
        public ActionResult Index()
        {
            return View(db.LoaiTVs.OrderBy(n => n.TenLoai));
        }

        [HttpGet]
        public ActionResult ChinhQuyen(int? id)
        {
            if(id==null)
            {
                Response.StatusCode = 404;
                return null;
            }
            LoaiTV ltv = db.LoaiTVs.SingleOrDefault(n => n.MaLoaiTV == id);
            if(ltv==null)
            {
                return HttpNotFound();
            }
            ViewBag.MaQuyen = db.Quyens;
            ViewBag.LoaiTVQuyen = db.LoaiTV_Quyens.Where(n => n.MaLoaiTV == id);
            return View(ltv);

        }
        [HttpPost]
        public ActionResult ChinhQuyen(int? MaLTV,IEnumerable<LoaiTV_Quyen> lstQuyen)
        {
            var lstDaPQ = db.LoaiTV_Quyens.Where(n => n.MaLoaiTV == MaLTV);
            if(lstDaPQ != null)
            {

                db.LoaiTV_Quyens.DeleteAllOnSubmit(lstDaPQ);
                db.SubmitChanges();
            }    
            foreach(var item in lstQuyen)
            {
                item.MaLoaiTV = int.Parse(MaLTV.ToString());
                
                db.LoaiTV_Quyens.InsertOnSubmit(item);
                   
            }
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/Views/Layouts/AdminLayout.cshtml
<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>Argon Dashboard - Free Dashboard for Bootstrap 4</title>
    <!-- Favicon -->
    <link rel="icon" href="~/Content/admin/assets/img/brand/favicon.png" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="~/Content/admin/assets/vendor/nucleo/css/nucleo.css" type="text/css">
    <link rel="stylesheet" href="~/Content/admin/assets/vendor/fortawesome/fontawesome-free/css/all.min.css" type="text/css">
    <!-- Page plugins -->
    <!-- Argon CSS -->
    <link rel="stylesheet" href="~/Content/admin/assets/css/argon.css?v=1.2.0" type="text/css">
</head>

<body>
    <!-- Sidenav -->
    <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
        <div class="scrollbar-inner">
            <!-- Brand -->
            <div class="sidenav-header  align-items-center">
                <a class="navbar-brand" href="javascript:void(0)">
                    <img src="~/Content/admin/assets/img/brand/blue.png" class="navbar-brand-img" alt="...">
                </a>
            </div>
            <div class="navbar-inner">
                <!-- Collapse -->
                <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                    <!-- Nav items -->
                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("QuanLySP","ADQuanLySP")">
                                <i class="ni ni-planet text-orange"></i>
                                <span class="nav-link-text">Quản lý sản phẩm</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("TaoMoi","ADQuanLySP")">
                                <i class="ni ni-pin-3 text-primary"></i>
                                <span class="nav-link-text">Tạo mới sản phẩm</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("ChuaGiao","QuanLyDH")">

                                <i class="ni ni-single-02 text-yellow"></i>
                                <span class="nav-link-text">Quản lý đơn hàng</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","ChinhQuyen")">
                                <i class="ni ni-bullet-list-67 text-default"></i>
                                <span class="nav-link-text">Chỉnh quyền</span>
                            </a>
                        </li>
                       

                    </ul>
                    <!-- Divider -->
                    <hr class="my-3">
                    <!-- Heading -->
                    <h6 class="navbar-heading p-0 text-muted">
                        <span class="docs-normal">Documentation</span>
                    </h6>
                    <!-- Navigation -->
                    <ul class="navbar-nav mb-md-3">
                        <li class="nav-item">
                            <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html" target="_blank">
                                <i class="ni ni-spaceship"></i>
                                <span class="nav-link-text">Getting started</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active active-pro" href="examples/upgrade.html">
                                <i class="ni ni-send text-dark"></i>
                                <span class="nav-link-text">Upgrade to PRO</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- Main content -->
    <div class="main-content" id="panel">
        @RenderBody();

    </div>
    
    <script src="~/Content/admin/assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/Content/admin/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/admin/assets/vendor/js-cookie/js.cookie.js"></script>
    <script src="~/Content/admin/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/Content/admin/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
    <!-- Optional JS -->
    <script src="~/Content/admin/assets/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="~/Content/admin/assets/vendor/chart.js/dist/Chart.extension.js"></script>
    <!-- Argon JS -->
    <script src="~/Content/admin/assets/js/argon.js?v=1.2.0"></script>
    
  
    <script>
        $("#btnInDonHang").click(function () {
            var content = "<table>" + $("#table").html() + "</table>";
            InDonHang(content);
        });
        function InDonHang(content) {
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title>DIV Contents</title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(content);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();

        }
    </script>
    <script>
    $(".pclick").click(function () {
        i = 0;
        $(".pclick").each(function () {
            if ($(this).is(':checked')) {
                $(this).attr("name", "[" + i + "].MaQuyen");
                i++;
            }
        })
    });
    </script>
    @RenderSection("script", false)
</body>

</html>

WebBanHang/Views/Layouts/TopPartial.cshtml
@using WebBanHang.Models;
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="text-slid-box">
                <div id="offer-box" class="carouselTicker">
                    <ul class="offer-box">
                        <li>
                            <i class="fab fa-opencart"></i> Off 10%! Shop Now Man
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> 50% - 80% off on Fashion
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> 20% off Entire Purchase Promo code: offT20
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> Off 50%! Shop Now
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> Off 10%! Shop Now Man
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> 50% - 80% off on Fashion
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> 20% off Entire Purchase Promo code: offT20
                        </li>
                        <li>
                            <i class="fab fa-opencart"></i> Off 50%! Shop Now
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="right-phone-box">
                <p>Call US :- <a href="#"> +11 900 800 100</a></p>
            </div>
            <div class="our-link">
                <ul>
                    @if (Session["TaiKhoan"] != null )
                    {
                        ThanhVien tv = (ThanhVien)Session["TaiKhoan"];
                        <li style="color:red">HELLO, @tv.HoTen</li>
                        @Html.ActionLink("Đăng Xuất", "DangXuat", "Home")
                    }
                    else
                    {
                        <li><a id="btndn" href="#">Login</a></li>
                        <li><a id="btndn" href="@Url.Action("DangKy","Home")">Register</a></li>
                    }

                </ul>
            </div>
        </div>
    </div>
</div>

<!--===============================================================================================-->
<link rel="icon" type="image/png" href="~/Content/images/icons/favicon.ico" />
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
<link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
<!--===============================================================================================-->

<div class="abc"> 
    <br />


    <div class="limiter">
        <div class="container-fluid">
            <div id="popup_login">
                <div class="wrap-login100">
                    <div style="clear:both;text-align:right;margin-bottom:0;">
                        <span id="close-form" class="btn btn-danger">X</span>
                    </div>

                    
                        @using (Html.BeginForm("DangNhap", "Home", FormMethod.Post,new {@class= "login100-form validate-form p-l-55 p-r-55 p-t-178" }))
                        {

                            <span class="login100-form-title">
                                Sign In
                            </span>

                            <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                                <input class="input100" type="text" name="username" placeholder="Username">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input" data-validate="Please enter password">
                                <input class="input100" type="password" name="pass" placeholder="Password">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="text-right p-t-13 p-b-23">
                                <span class="txt1">
                                  
                                </span>
                                <h3 style="font-weight:bold;color:red;text-align:left;" id="ThongBao">  </h3>
                                <a href="#" class="txt2">
                                    
                                </a>
                            </div>

                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn" id=" btnDN">
                                    Sign in
                                </button>
                            </div>

                            <div class="flex-col-c p-t-170 p-b-40">
                                <span class="txt1 p-b-9">
                                    Don’t have an account?
                                </span>

                                <a href="@Url.Action("DangKy","Home")" class="txt3">
                                    Sign up now
                                </a>
                            </div>}
                    

                </div>
            </div>
        </div>
    </div>
</div>
<!--===============================================================================================-->
<script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/bootstrap/js/popper.js"></script>
<script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/daterangepicker/moment.min.js"></script>
<script src="~/Content/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/Content/js/main.js"></script>
<script>
    $("#btndn").click(function () {
        $("#popup_login").show();
    });
    $("#close-form").click(function () {
        $("#popup_login").hide();
    });

</script>





<style>
    .abc {
        position: absolute;
        top: 10%;
        left: 35%;
        z-index: 10;
    }
</style>