WebBanHang/Controllers/ADQuanLySPController.cs
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class ADQuanLySPController : Controller
    {
        BanHangDataContext db = new BanHangDataContext();
        // GET: ADQuanLySP
        public ActionResult QuanLySP()
        {
            return View(db.SanPhams.Where(n => n.DaXoa == false));
        }
        [HttpGet]
        public ActionResult TaoMoi()
        {
            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(SanPham sp, HttpPostedFileBase HinhAnh)
        {

            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            //Ktra Hinh anh
            if (HinhAnh.ContentLength > 0)
            {
                var filename = Path.GetFileName(HinhAnh.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/HinhSP/"), filename);
                if (System.IO.File.Exists(path))
                {
                    ViewBag.upload = "Hình ảnh đã tồn tại";
                    return View();
                }
                else
                {
                    HinhAnh.SaveAs(path);
                    sp.HinhAnh = filename;


                }


            }
            db.SanPhams.InsertOnSubmit(sp);
            db.SubmitChanges();
            return RedirectToAction("QuanLySP");

        }
        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
            return View(sp);
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(SanPham model)
        {
           

            ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", model.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", model.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", model.MaNSX);
            SanPham sp = db.SanPhams.Single(n => n.MaSP == model.MaSP);
            sp.TenSP = model.TenSP;
            sp.SoLuongTon = model.SoLuongTon;
            sp.NgayCapNhat = model.NgayCapNhat;
            sp.Moi = model.Moi;
            sp.MoTa = model.MoTa;
            sp.CauHinh = model.CauHinh;
            sp.DonGia = model.DonGia;
            
            db.SubmitChanges();
            return RedirectToAction("QuanLySP");
            
        }
        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            {
                if (id == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
                if (sp == null)
                {
                    return HttpNotFound();
                }
                ViewBag.MaNCC = new SelectList(db.NhaCCs.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
                ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
                ViewBag.MaNSX = new SelectList(db.NhaSXes.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
                return View(sp);
            }
        }
        [HttpPost]
        public ActionResult Xoa(int? id,FormCollection f)
        {
            {
                if (id == null)
                {

                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
                if (sp == null)
                {
                    return HttpNotFound();
                }
                db.SanPhams.DeleteOnSubmit(sp);
                db.SubmitChanges(); ;
                return RedirectToAction("QuanLySP");

            }
        }
    }
}

WebBanHang/Controllers/HomeController.cs
using CaptchaMvc.HtmlHelpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class HomeController : Controller
    {
        BanHangDataContext db = new BanHangDataContext();
        public ActionResult Index()
        {
            var lstSP = db.SanPhams.Where(n => n.MaLoaiSP == 2 && n.Moi == 1 && n.DaXoa == false);
            ViewBag.ListSP = lstSP;
            return View();
        }


        public ActionResult MenuPartial()
        {
            var lstSP = db.SanPhams;
            return PartialView(lstSP);
        }
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(ThanhVien tv)
        {
            //Ktra captch
            if (this.IsCaptchaValid("Captcha is not valid"))
            {
                ViewBag.ThongBao = "ĐĂNG KÍ THÀNH CÔNG";
                db.ThanhViens.InsertOnSubmit(tv);
                db.SubmitChanges();


                //db.ThanhViens.(tv);
                //db.SaveChanges();

                return View();
            }
            ViewBag.ThongBao = "Sai mã";
            return View();
        }
        // Dang nhap
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string tk = f["username"].ToString();
            string mk = f["pass"].ToString();
            ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.TaiKhoan == tk && n.MatKhau == mk);
            if (tv != null)
            {
                var lstquyen = db.LoaiTV_Quyens.Where(n => n.MaLoaiTV == tv.MaLoaiTV);
                string Quyen = "";
                foreach (var item in lstquyen)
                {
                    Quyen += item.Quyen.MaQuyen + ",";
                }
                Quyen = Quyen.Substring(0, Quyen.Length - 1);
                
                PhanQuyen(tv.TaiKhoan.ToString(), Quyen);
                Session["TaiKhoan"] = tv;
                if (tv.MaLoaiTV == 3) { return RedirectToAction("Index");}
                else { return RedirectToAction("QuanLySP","ADQuanLySP"); }
                
            }
            return Content("Tài khoản hoặc mật khẩu không đúng");
        }
        public void PhanQuyen(string tk, string q)
        {
            FormsAuthentication.Initialize();
            var ticket = new FormsAuthenticationTicket(1, tk, DateTime.Now, DateTime.Now.AddHours(3), false, q, FormsAuthentication.FormsCookiePath);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
            if (ticket.IsPersistent) cookie.Expires = ticket.Expiration;
            Response.Cookies.Add(cookie);
        }
        public ActionResult LoiPhanQuyen()
        {
            return View();
        }
        public ActionResult DangXuat()
        {
            Session["TaiKhoan"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

    }
}

WebBanHang/Controllers/TimKiemController.cs
using PagedList;
using System.Linq;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class TimKiemController : Controller
    {
        BanHangDataContext db = new BanHangDataContext();
        // GET: TimKiem
        [HttpGet]
        public ActionResult KQTimKiem(string tukhoa, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int Pagesize = 3;
            int Pagenum = (page ?? 1);
            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(tukhoa));
            ViewBag.TuKhoa = tukhoa;
            return View(lstSP.OrderBy(n => n.TenSP).ToPagedList(Pagenum, Pagesize));
        }
        [HttpPost]
        public ActionResult TimKiemTu(string tukhoa)
        {

            return RedirectToAction("KQTimKiem", new { @tukhoa = tukhoa });
        }

    }
}

WebBanHang/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebBanHang/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebBanHang/Views/Home/DangKy.cshtml
@using WebBanHang.Models;
@using CaptchaMvc.HtmlHelpers
@using CaptchaMvc
@model ThanhVien
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Layouts/HomeLayout.cshtml";
}

<div class="cart-box-main">
    <div class="container">
        @using (Html.BeginForm())
        {
            <div class="row new-account-login">
                <div class="col-sm-6 col-lg-6 mb-3">

                    <div class="title-left">
                        <h3>Tạo tài khoản</h3>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="InputEmail" class="mb-0">Tài khoản</label>
                        @Html.TextBox("TaiKhoan")
                    </div>
                    <div class="form-group col-md-6">
                        <label for="" class="mb-0">Họ tên</label>
                        @Html.TextBox("HoTen")
                    </div>
                    <div class="form-group col-md-6">
                        <label for="InputPassword3" class="mb-0">Địa chỉ</label>
                        @Html.TextBox("DiaChi")
                    </div>
                    <div class="form-group col-md-6">
                        <label for="InputEmail2" class="mb-0">Email</label>
                        @Html.TextBox("Email")
                    </div>



                </div>
                <div class="col-sm-6 col-lg-6 mb-3">
                    <div class="title-left">
                        <h3>Tạo tài khoản</h3>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="InputName" class="mb-0">Mật khẩu</label>
                        @Html.Password("MatKhau")
                    </div>
                    <div class="form-group col-md-6">
                        <label for="InputLastname" class="mb-0">Số Điện Thoại</label>
                        @Html.TextBox("SoDT")
                    </div>
                    <div class="form-group col-md-6">
                        <label for="InputEmail1" class="mb-0">Câu hỏi bí mật</label>
                        @Html.TextBox("CauHoi")
                    </div>
                    <div class="form-group col-md-6">
                        <label for="InputPassword1" class="mb-0">Câu trả lời</label>
                        @Html.TextBox("CauTraLoi")
                    </div>
                    <div>@Html.MathCaptcha()</div>
                    <button type="submit" class="btn hvr-hover">Register</button>

                </div>

            </div>
        }
    </div>
</div>
<h1 style="color:red;">@ViewBag.ThongBao</h1>

WebBanHang/Views/Home/Index.cshtml
@using WebBanHang.Models;
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/HomeLayout.cshtml";
}
@{
    IEnumerable<SanPham> lstLT = (IEnumerable<SanPham>)ViewBag.ListSP;
}


<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="title-all text-center">
                <h1>LapTop</h1>
            </div>
        </div>
    </div>


    @Html.Partial("~/Views/SanPham/SanPhamPartial1.cshtml", lstLT)
</div>


<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="title-all text-center">
                <h1>LapTop</h1>
            </div>
        </div>
    </div>
    <div class="container">
        @Html.Partial("~/Views/SanPham/SanPhamPartial2.cshtml", lstLT)

    </div>
</div>

WebBanHang/Views/Home/LoiPhanQuyen.cshtml
@{
    ViewBag.Title = "LoiPhanQuyen";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

<h2>BẠN KHÔNG ĐỦ QUYỀN TRUY CẬP VÀO MỤC NÀY VUI LÒNG TRỞ LẠI @Html.ActionLink("Trở về","QuanLySP","ADQuanLySP")</h2>

WebBanHang/Views/Home/MenuPartial.cshtml
@using WebBanHang.Models;
@model IEnumerable<SanPham>


           
<div class="navbar-header">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="toggle navigation">
        <i class="fa fa-bars"></i>
    </button>
    <a class="navbar-brand" href="@Url.Action("index","home")"><img src="~/content/images/logo.png" class="logo" alt=""></a>
</div>
<div class="collapse navbar-collapse" id="navbar-menu">
    <ul class="nav navbar-nav ml-auto" data-in="fadeindown" data-out="fadeoutup">
        <li class="nav-item active"><a class="nav-link" href="@Url.Action("index","home")">Home</a></li>

       
                            @foreach (var groupItem in Model.GroupBy(n => n.LoaiSP))
                            {
                                if (groupItem.Key != null)
                                {
                                    
                                            foreach (var item in groupItem.GroupBy(n => n.NhaSX))
                                            {
                                                if (item.Key != null)
                                                {
                                                    <li class= "nav-item active"><a class="nav-link"  href="@Url.Action("SanPham","SanPham",new { @MaLoaiSP = groupItem.Key.MaLoaiSP,@MaNSX=item.Key.MaNSX })">@item.Key.TenNSX</a></li>

                                                }
                                            }


                                }
                            } 
                        


      
        


    </ul>
    @*@using (Html.BeginForm("TimKiemTu", "TimKiem"))
    {
        <div class="top-search">
            <div class="container">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input type="text" name="tukhoa" class="form-control" placeholder="Search">
                    <span class="input-group-addon search"><i class="fa fa-times"></i></span>
                </div>
            </div>
        </div>
    }*@
</div>
      